### ISSUE TITLE
Failing to start. DNS name does not have enough labels

### ISSUE THREAD

**Issue by NickWilton** [jgillich/hyper-proxy#5]
Since the GZIP update, I'm now getting the following error and the proxy is failing to start.
Googling a bit, it appears that the error message "DNS name does not have enough labels" appears to be specific to Let's Encrypt.

```
> hyper-proxy@0.1.0 start /app
> node index.js

Activating privacy features...
2017/03/10 22:50:39 [gzip] failed to get certificate: acme: Error 400 - urn:acme:error:malformed - DNS name does not have enough labels


npm ERR! Linux 4.4.28-hyper
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hyper-proxy@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hyper-proxy@0.1.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hyper-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hyper-proxy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hyper-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

> hyper-proxy@0.1.0 start /app
> node index.js

Unhandled rejection FetchError: request to https://us-west-1.hyper.sh/containers/json failed, reason: getaddrinfo EAI_AGAIN us-west-1.hyper.sh:443
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Cheers.

**Comment by NickWilton** [comment]
npm is no longer a dependency of nodejs. So this now needs to be installed explicitly.
